// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl4iAE5GxTyN1IgYyoKnRrTw-6QoOc7y4',
    appId: '1:599906860098:web:9939b9f0759ac68e04c1db',
    messagingSenderId: '599906860098',
    projectId: 'mini-twitter-dev',
    authDomain: 'mini-twitter-dev.firebaseapp.com',
    storageBucket: 'mini-twitter-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgnxvnwNEALCKarihnVHf7rHIBAUpEnk',
    appId: '1:599906860098:android:0d793fa2d4f287fc04c1db',
    messagingSenderId: '599906860098',
    projectId: 'mini-twitter-dev',
    storageBucket: 'mini-twitter-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwYqKMe9rOjy3ou1nK-ZnzHE14u3-gik',
    appId: '1:599906860098:ios:f3d69296b5ffc84f04c1db',
    messagingSenderId: '599906860098',
    projectId: 'mini-twitter-dev',
    storageBucket: 'mini-twitter-dev.firebasestorage.app',
    iosBundleId: 'com.example.miniTwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwYqKMe9rOjy3ou1nK-ZnzHE14u3-gik',
    appId: '1:599906860098:ios:f3d69296b5ffc84f04c1db',
    messagingSenderId: '599906860098',
    projectId: 'mini-twitter-dev',
    storageBucket: 'mini-twitter-dev.firebasestorage.app',
    iosBundleId: 'com.example.miniTwitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl4iAE5GxTyN1IgYyoKnRrTw-6QoOc7y4',
    appId: '1:599906860098:web:681a784ac2f0f2fc04c1db',
    messagingSenderId: '599906860098',
    projectId: 'mini-twitter-dev',
    authDomain: 'mini-twitter-dev.firebaseapp.com',
    storageBucket: 'mini-twitter-dev.firebasestorage.app',
  );
}
